package-lock.json
package.json

Release: 0.1.1

---

src/api/index.ts

This PR adds CORS headers, so that we don't run into CORS-related issues with the VHS.
I was running into issues with CORS from the VHS.
Not sure how to test this fix.

fix: add CORS headers

---

.github/workflows/node.js.yml

This PR adds automatic testing for every PR via Github Actions.
Automatic testing for PRs
Tests pass in CI.

test: Add Github Actions automatic testing

---

package.json
src/crawler/index.ts

See #25 
See #25
CI passes. Works in staging and locally.

fix: fix crawler crossing network boundaries

---

package-lock.json
package.json

Title says it all
0.1.5 didn't actually have all the changes.
N/A

release: update version to 0.1.6

---

src/shared/utils/networks.ts

This PR can also serve as a template for how to add a new network to the VHS.
This will allow us to support the networks page on the Explorer for NFT-Devnet.
Works locally.

feat: add NFT-Devnet to the list of networks

---

src/shared/database/setup.ts

https://github.com/ripple/validator-history-service/pull/35 contains a db migration. This handles that programmatically.
Tested locally, it works.

chore: handle migration for hourly and daily agreement tables

---

.github/workflows/node.js.yml
package.json
src/connection-manager/index.ts
src/crawler/index.ts

This PR resolves issues with deployment.
I was having issues deploying the latest version to staging. It turns out that the dev commands call the scripts in a different manner than the prod commands.
Works in staging.

fix: resolve issue with deployment

---

package.json
src/api/routes/v1/index.ts
src/api/routes/v1/info.ts
src/api/routes/v1/validator.ts

This PR fixes the validator API endpoint so that it actually works as expected. This involves a change from taking a network to taking a UNL.
The data in the database was organized differently than I thought.
Works locally. CI passes.

fix: validator API endpoint wasn't showing anything

---

package-lock.json
package.json

Published the new version
CI passes.

publish: bump version to 0.2.0

---

package-lock.json
package.json

Changes version to 0.3.0 for release.

set version to 0.3.0

---

ARCHITECTURE.md
src/shared/database/setup.ts

Delete the ledger table in VHS since it is not being used at the moment.
Table `ledgers` would be remove from the schema.

clean-ups: remove unused ledgers table

---

src/api/routes/v1/info.ts

Noticed when working on the Explorer
Fixed typos
N/A

fix: fix typos in the API info list

---

package-lock.json
package.json

set version to 0.4.0

---

package-lock.json
package.json

publish: bump version to 0.4.1

---

src/shared/database/networks.ts
src/shared/database/setup.ts

fix: remove nft-dev network

---

package-lock.json
package.json

update version to 0.4.3

---

src/shared/database/networks.ts
src/shared/database/setup.ts

This PR removes the Coil UNL (which no longer exists) and fixes a db error on the `incomplete_shards` key in `crawls`.
Fixing bugs that cropped up while working on #97 
Works locally.

fix: assorted fixes

---

src/connection-manager/wsHandling.ts

The tests for adding amendments status are flaky due to the use of `forEach`, which does not work well with asynchronous operations. The use of `Promise.all()` with `map()` should fix this issue ([reference](https://gist.github.com/joeytwiddle/37d2085425c049629b80956d3c618971))

fix: flaky amendment test

---

ARCHITECTURE.md
src/api/routes/v1/index.ts
src/api/routes/v1/info.ts
src/api/routes/v1/networks.ts
test/api/networks.test.ts

Add `\networks` endpoint to display all networks/ sidechains on VHS database. Would be useful for internal development, other API calls, and DID tooling.

feat: add `/networks` api

---

src/shared/database/amendments.ts

Known amendment xrpl.org is now at:
https://raw.githubusercontent.com/XRPLF/xrpl-dev-portal/master/resources/known-amendments.md

fix: update amendment rippled version data source

---

package-lock.json
package.json

Release 0.7.1

---

src/shared/database/amendments.ts

The link to populate amendment names by id has been changed to:
https://raw.githubusercontent.com/XRPLF/rippled/develop/src/libxrpl/protocol/Feature.cpp

fix: update amendment rippled link

---

package-lock.json
package.json

release 0.8.0

---

src/connection-manager/connections.ts
tsconfig.json

fix npm build

---

package-lock.json
package.json

Release 0.8.2. This would contain a hot fix to recent websocket connections issue. Reassessment will be deployed in future release

release 0.8.2

---

package-lock.json
package.json

This release removed database calls to fetch validators to avoid swamping database with multiple requests on each validation.

release 0.8.3-rc.2

---

package-lock.json
package.json

release 0.8.3

---

package-lock.json
package.json

release 0.8.4

---

src/api/routes/v1/amendments.ts
src/api/routes/v1/daily-report.ts
src/api/routes/v1/get-network.ts
src/api/routes/v1/health.ts
src/api/routes/v1/manifests.ts
src/api/routes/v1/networks.ts
src/api/routes/v1/nodes.ts
src/api/routes/v1/validator-report.ts
src/api/routes/v1/validator.ts
test/api/networks.test.ts
test/api/validators.test.ts

This PR updates the responses of the API endpoints with non-breaking changes.
- Error Cases are appended with explanatory error messages (commit: 33e141998af530bb9c411505c8e0df0ef05fb8f0). This does not incur any privacy violations. The VHS software is open-source and can be deployed/run by anybody in the world. The stack-traces/logs in the production VHS are identical to any other deployments of the VHS.
- All the API responses are associated with an HTTP status code (success: 200; failure: 404, 500). This is helpful for monitoring the health of the service.
The existing unit tests have been updated to account for HTTP status codes. Mock functions have been used in-place of the status method.

Update responses of API endpoints

---

package-lock.json
package.json

release v0.8.5

---

.github/workflows/node.js.yml

Make `npm ci` more stricter in CI pipeline by removing `--legacy-peer-deps`. This avoids the risk of incompatible versions of libraries being installed.

Make npm ci more stricter in CI pipeline

---

package-lock.json
package.json

This PR will fix unintended container restart issue caused due to error thrown from xrpl.js.
More details can be found in xrpl.js [PR](https://github.com/XRPLF/xrpl.js/pull/3065).
Tested on staging environment that container no more restarts with the unhandled `XrplError`. It's a dependency update so existing test cases should pass.

Update xrpl package to v4.4.1
